name: BanTools
version: 1.0.1
api: [3.0.0-ALPHA9, 2.1.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: StrafelessPvP
main: Tool\Main
commands:
 invisible:
  description: Make you a ghost
  permission: voidminerpe.invisible
  default: op
 visible:
  description: Make you visible to players
  permission: voidminerpe.visible
  default: op
 vmban:
  description: Ban players
  permission: voidminerpe.ban
  default: op
 vmpardon:
  description: Pardon any which is banned
  permission: voidminerpe.pardon
  default: op
 vminfo:
  description: See any player information
  permission: voidminerpe.info
  default: op
 vmfreeze:
  description: Freeze and unFreeze any player
  permission: voidminerpe.freeze
  default: op
 adminchat:
  description: Chat just for op
  permission: voidminerpe.adminchat
  default: op
 tools:
  description: Check all commands
  permission: voidminerpe.tools
  default: op
